services:
  backend:
    build: ./backend
    container_name: myfinance-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/data:/app/app/data
    restart: unless-stopped
    environment:
      - TZ=UTC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    build: ./frontend
    container_name: myfinance-frontend
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - TZ=UTC
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  myfinance-data:
    driver: local